Dev js first part tasks
KubaKlin/wanacode-html pull request #6
Opened 2024-10-09 09:57 UTC by KubaKlin

2024-10-10 18:48 UTC, Solnick requested changes

2024-10-10 18:48 UTC, Solnick commented on tasks1.js
> +}
> Otherwise, print "Try harder!"

You forgot about this

2024-10-10 18:48 UTC, Solnick commented on tasks1.js
> +let VATRateInPoland = 0.23;
this can be `const`

2024-10-10 18:48 UTC, Solnick commented on tasks1.js
> +let monthlyIncome = 3500;
this can be const

2024-10-10 18:48 UTC, Solnick commented on tasks1.js
> +if ( currentMonth === 12 || currentMonth === 1 || currentMonth === 2 ) {
```suggestion
if (currentMonth === 12 || currentMonth === 1 || currentMonth === 2) {
```
Please be consistent in code formatting

2024-10-10 18:48 UTC, Solnick commented on tasks1.js
> +} else if (currentMonth === 3 || currentMonth === 4 || currentMonth === 5) {
```suggestion
} else if (currentMonth >= 3 || currentMonth <= 5) {
```
Let's make it simpler

2024-10-10 18:48 UTC, Solnick commented on tasks1.js
> +}
Good! Can be done better ;)
```suggestion
const isAdult = ageVariable >= 18
```

2024-10-10 18:48 UTC, Solnick commented on tasks1.js
> +}
Almost
```suggestion
const canDriveLegally = isPersonAdult && hasDrivingLicense

if (canDriveLegally) {
  console.log('This person can legally drive');
} else {
  console.log("This person can't legally drive");
}
```

2024-10-10 18:48 UTC, Solnick commented on tasks1.js
> +}
Maybe it can be simplified further…

2024-10-14 21:24 UTC, mwanago commented on tasks1.js
> +  console.log('a citizen can vote');
Use either `"` or `'`, but be consistent

2024-10-16 22:36 UTC, mwanago commented on index.html
> +
This empty line is not necessary

2024-10-18 07:49 UTC, mwanago approved these changes

2024-10-18 08:35 UTC, merged